### PR TITLE
Some manual fixes

### PR DESCRIPTION
**Pull request by olexandr-konovalov**
I had a look at the manual, but I can't reproduce the error message that you included in your email about `<#Include Label="ChangeBasis">`. On the way, I have made a couple of fixes, addressing some of the errors reported after running `doc/buildman.g`. Also, the usual and recommended practice is to not to keep derived files under version control, instead, the manual is generated when release is made.

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
@nzidaric what to do with this PR? If all suggestions have already been addresses, shall we just close it?

**Comment by nzidaric** [comment]
Hello!

I just got back into my gap code this week, im planning on getting this
finished by the end of the week. Is it OK if I get back to You on monday ?


How was Your summer so far ?

best regards
nusa zidaric

**Comment by olexandr-konovalov** [comment]
Fine, thanks - just take your time, there is no rush with this.

**Comment by nzidaric** [comment]
fixed  Fixed typo in cross-reference and  There is no such entirty &LFSR; defined 

but not the doc/

**Pull request closed without merging**
