### PR TITLE
Improve Markdown formatting of README.md

### PR DESCRIPTION
**Pull request by slel**
This will help the code parts appear properly
on GitHub's rendering of the README page.

### CODE REVIEW

**Comment by olexandr-konovalov** [comment]
@nzidaric could you please reopen this PR? It was closed accidentally when we pulled GitHubPagesForGAP (this should not happen, accordingly to GitHub documentation, but we observed this several times with @fingolfin)

**Comment by nzidaric** [comment]
ok, im lost ?

im guessing PR = pull request




________________________________

**Comment by nzidaric** [comment]
found it :)

**Comment by slel** [comment]
Yes, PR = pull request. You can even "merge"
if you consider it useful.

**Review by olexandr-konovalov — APPROVED** [review]

**Comment by slel** [comment]
@alex-konovalov thanks for approving the changes.
@nzidaric do you want to press the "merge" button?

**Pull request merged**
